# Generated by Django 3.2.6 on 2021-09-07 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.CharField(max_length=255, null=True)),
                ('autor', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('megusta_users', models.ManyToManyField(related_name='me_gusta', to='app.User')),
                ('posteado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_posteadas', to='app.user')),
            ],
        ),
    ]
