# Generated by Django 3.2.6 on 2021-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_quote_megusta_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='megusta_users',
            field=models.ManyToManyField(related_name='me_gusta', to='app.User'),
        ),
    ]
